apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret
  namespace: odoo
type: generic
stringData:
  AWS_ACCESS_KEY_ID: "AKIAWN26EQBPVMVZV5P4"
  AWS_SECRET_ACCESS_KEY: "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"
  AWS_DEFAULT_REGION: "us-east-2"
